spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: update